"""Daily inference using the saved notebook models and the same engineered features.

No re-training occurs here. A completed daily close is required for a new prediction.
Yahoo data may be delayed, blocked, or incomplete; failures are surfaced to the UI.
"""
from datetime import datetime, time, timedelta
from pathlib import Path
from zoneinfo import ZoneInfo
import joblib
import numpy as np
import pandas as pd
import yfinance as yf

ROOT = Path(__file__).resolve().parent
MODEL_DIR = ROOT / 'models'
CACHE_DIR = ROOT / '.cache'
CACHE_DIR.mkdir(exist_ok=True)
REQUIRED_PRICES = ['Open', 'High', 'Low', 'Close', 'Volume']
HORIZONS = (5, 10)


def completed_session_cutoff(now=None):
    now = now or datetime.now(ZoneInfo('America/New_York'))
    local = now.astimezone(ZoneInfo('America/New_York'))
    day = local.date()
    if local.time() < time(17, 0):
        day -= timedelta(days=1)
    while day.weekday() >= 5:
        day -= timedelta(days=1)
    return pd.Timestamp(day)


def load_bundles():
    files = [MODEL_DIR / f'{h}d.joblib' for h in HORIZONS]
    universe_file = MODEL_DIR / 'universe.csv'
    if not all(p.is_file() for p in [*files, universe_file]):
        raise FileNotFoundError('Saved models are missing. Run the last Save models cell of the notebook once and copy the models folder next to app.py.')
    # Only load model bundles generated by your own notebook. joblib files can run code when loaded.
    bundles = {h: joblib.load(MODEL_DIR / f'{h}d.joblib') for h in HORIZONS}
    sectors = pd.read_csv(universe_file, dtype={'Ticker':str,'Sector':str})
    if any(bundles[h].get('format_version') != 1 for h in HORIZONS):
        raise ValueError('Unsupported model bundle version. Re-run Save models in the updated notebook.')
    if bundles[5]['features'] != bundles[10]['features']:
        raise ValueError('The two model bundles use different feature definitions.')
    sectors = sectors.dropna(subset=['Ticker', 'Sector']).drop_duplicates(subset=['Ticker'])
    return bundles, sectors


def _download_bars(tickers, cutoff, downloader=None):
    downloader = downloader or yf.download
    start=(cutoff - pd.Timedelta(days=825)).strftime('%Y-%m-%d')
    end=(cutoff + pd.Timedelta(days=1)).strftime('%Y-%m-%d')
    chunks=[]
    # Smaller requests have fewer partial failures than a single 500-ticker request.
    for offset in range(0, len(tickers), 70):
        symbols=tickers[offset:offset+70]
        batch=downloader(symbols, start=start, end=end, auto_adjust=False,
                         group_by='column', threads=True, progress=False)
        if batch is None or batch.empty:
            continue
        if not isinstance(batch.columns, pd.MultiIndex):
            if len(symbols) == 1:
                batch.columns=pd.MultiIndex.from_product([batch.columns, symbols], names=['Price','Ticker'])
            else:
                continue
        if 'Ticker' not in batch.columns.names:
            # yf.download(group_by='column') returns Price then Ticker.
            batch.columns=batch.columns.set_names(['Price','Ticker'])
        chunks.append(batch)
    if not chunks:
        raise RuntimeError('Yahoo Finance returned no usable daily bars. Check your internet connection and try again later.')
    wide=pd.concat(chunks,axis=1)
    # Some tickers may fail; do not create fake prices for them.
    long=wide.stack(level='Ticker', future_stack=True).reset_index()
    long=long.dropna(subset=REQUIRED_PRICES)
    long['Date']=pd.to_datetime(long['Date']).dt.tz_localize(None).dt.normalize()
    long=long.loc[long['Date']<=cutoff].sort_values(['Ticker','Date']).reset_index(drop=True)
    if long.empty:
        raise RuntimeError('No completed daily bars were returned.')
    return long

def create_features(group):
    group = group.sort_values('Date').copy()
    close = group['Close']

    group['Daily_Return'] = close.pct_change(fill_method=None)
    group['Return_5d'] = close.pct_change(5, fill_method=None)
    group['Return_20d'] = close.pct_change(20, fill_method=None)

    sma20 = close.rolling(20).mean()
    sma50 = close.rolling(50).mean()
    group['Price_SMA20_Distance'] = (close - sma20) / sma20
    group['Price_SMA50_Distance'] = (close - sma50) / sma50

    group['Volatility_20'] = group['Daily_Return'].rolling(20).std()
    group['High_Low_Range_Pct'] = (group['High'] - group['Low']) / close
    group['Volume_Ratio_20'] = group['Volume'] / (group['Volume'].rolling(20).mean() + 1e-8)

    delta = close.diff()
    gain = delta.where(delta > 0, 0).rolling(14).mean()
    loss = -delta.where(delta < 0, 0).rolling(14).mean()
    rs = gain / (loss + 1e-8)
    group['RSI_14'] = 100 - (100 / (1 + rs))

    std20 = close.rolling(20).std()
    upper = sma20 + 2 * std20
    lower = sma20 - 2 * std20
    group['BB_Percent_B'] = (close - lower) / (upper - lower + 1e-8)

    group['ROC_10'] = close.pct_change(10, fill_method=None)

    ema12 = close.ewm(span=12, adjust=False).mean()
    ema26 = close.ewm(span=26, adjust=False).mean()
    group['EMA_Spread_Pct'] = (ema12 - ema26) / close

    previous_close = close.shift(1)
    true_range = pd.concat(
        [
            group['High'] - group['Low'],
            (group['High'] - previous_close).abs(),
            (group['Low'] - previous_close).abs(),
        ],
        axis=1,
    ).max(axis=1)
    group['ATR_14_Pct'] = true_range.rolling(14).mean() / close

    high_252 = group['High'].rolling(252).max()
    low_252 = group['Low'].rolling(252).min()
    group['Position_52w'] = (close - low_252) / (high_252 - low_252 + 1e-8)

    return group



def engineer_features(long_data, sector_lookup):
    # This is the same feature calculation as the training notebook.
    parts = [create_features(group) for _, group in long_data.groupby('Ticker', sort=False)]
    features = pd.concat(parts, ignore_index=True)
    market_stats = (features.groupby('Date')['Daily_Return']
                    .agg(['mean','std']).rename(columns={'mean':'Market_Mean','std':'Market_Std'}))
    features = features.merge(market_stats, on='Date', how='left')
    features['Relative_Return_Z'] = ((features['Daily_Return'] - features['Market_Mean']) /
                                      (features['Market_Std'] + 1e-8))
    features = features.drop(columns=['Market_Mean','Market_Std'])
    features = features.merge(sector_lookup[['Ticker','Sector']], on='Ticker', how='left')
    sector_stats=(features.groupby(['Date','Sector'])['Daily_Return']
                  .agg(['mean','std']).rename(columns={'mean':'Sector_Mean','std':'Sector_Std'}))
    features=features.merge(sector_stats,on=['Date','Sector'],how='left')
    features['Relative_Return_Sector_Z']=((features['Daily_Return']-features['Sector_Mean']) /
                                          (features['Sector_Std']+1e-8))
    return features.drop(columns=['Sector_Mean','Sector_Std'])


def predict_with_bundle(bundle, X):
    X_scaled = None
    columns=[]
    for name in bundle['model_names']:
        if name in {'LightGBM','HistGradientBoosting'}:
            pred = bundle['models'][name].predict(X)
        else:
            if X_scaled is None:
                X_scaled = bundle['scaler'].transform(X).astype(np.float32)
            pred = bundle['models'][name].predict(X_scaled)
        columns.append(np.asarray(pred, dtype=float))
    return np.column_stack(columns) @ np.asarray(bundle['weights'], dtype=float)


def predict_from_bars(long_data, bundles, sector_lookup, cutoff=None):
    all_features=engineer_features(long_data,sector_lookup)
    feature_names=bundles[5]['features']
    all_features[feature_names]=all_features[feature_names].replace([np.inf,-np.inf],np.nan)
    latest_date=all_features['Date'].max()
    # If Yahoo returns a partial last day for very few companies, do not treat it as a full market snapshot.
    counts=all_features.groupby('Date')['Ticker'].nunique()
    sufficient=counts[counts >= max(2, int(len(sector_lookup)*0.7))]
    if sufficient.empty:
        raise RuntimeError('Insufficient stocks have completed daily data for cross-sectional indicators.')
    date=sufficient.index.max()
    if cutoff is not None and (pd.Timestamp(cutoff) - date).days > 5:
        raise RuntimeError(f'Data too old for a new forecast: latest complete market snapshot is {date.date()}.')
    today=(all_features.loc[all_features['Date'].eq(date)]
           .dropna(subset=feature_names + ['Close']).copy().reset_index(drop=True))
    if today.empty:
        raise RuntimeError('No stocks have a complete set of features for the latest date.')
    ui=today[['Ticker','Date','Close']].rename(columns={'Close':'Current_Price'}).copy()
    for horizon in HORIZONS:
        bundle=bundles[horizon]
        raw=predict_with_bundle(bundle,today[feature_names])
        reference=np.asarray(bundle['confidence_reference'], dtype=float)
        confidence=np.searchsorted(reference,np.abs(raw),side='right')/len(reference)*100
        strength=np.clip((confidence-50)/50,0,1)
        calibrated=raw*(1+0.25*strength**1.5)
        ui[f'{horizon}D_Raw_Return']=raw
        ui[f'{horizon}D_Calibrated_Return']=calibrated
        ui[f'{horizon}D_Confidence']=confidence
        ui[f'{horizon}D_Raw_Price']=ui['Current_Price']*(1+raw)
        ui[f'{horizon}D_Display_Price']=ui['Current_Price']*(1+calibrated)
    history=(long_data[['Ticker','Date','Close']]
             .sort_values(['Ticker','Date']).groupby('Ticker',sort=False).tail(300))
    return ui,history


def latest_forecasts(force=False, downloader=None, now=None):
    bundles,sectors=load_bundles()
    cutoff=completed_session_cutoff(now)
    # Version the cache by cutoff and model file modification times.
    version='_'.join(str((MODEL_DIR/f'{h}d.joblib').stat().st_mtime_ns) for h in HORIZONS)
    key=f'{cutoff:%Y%m%d}_{version}'
    signal_cache=CACHE_DIR/f'signals_{key}.pkl'
    history_cache=CACHE_DIR/f'history_{key}.pkl'
    if not force and signal_cache.is_file() and history_cache.is_file():
        return pd.read_pickle(signal_cache), pd.read_pickle(history_cache)
    tickers=sectors['Ticker'].tolist()
    bars=_download_bars(tickers,cutoff,downloader=downloader)
    ui,history=predict_from_bars(bars,bundles,sectors,cutoff=cutoff)
    ui.to_pickle(signal_cache)
    history.to_pickle(history_cache)
    return ui,history
